package utility.Components;

import GUI.Window;
import java.awt.Dimension;

/**
 *
 * @author thomi
 */
public class ShowTestResult extends javax.swing.JFrame {

    /**
     * Creates new form ShowTestResult - this window serves as a evaluation of the test, gives correct answers / total answers.
     */
    public ShowTestResult() {
        initComponents();
    }
    /**
     * This function dusplays the amount of correctly answered questions
     * @param nRights - how many questions were asnwered correctly
     * @param qCount - total question count
     */
    public ShowTestResult(int nRights,int qCount) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Výsledek testu");
        this.setPreferredSize(new Dimension(170,60));
        jLabel1.setText("Povedlo se vám zodpovědět správně "+ jLabel1.getText() + nRights+" z "+qCount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Zpět do menu");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMenu(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method returns back to menu
     * @param evt 
     */
    private void backToMenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMenu
        Window.getInstance().changePanel(new Settings());
        Window.getInstance().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backToMenu


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
